### ISSUE TITLE
Connect-PveCluster

### ISSUE THREAD

**Issue by flaviol** [Corsinvest/cv4pve-api-pwsh#1]
Why the Connect-PveCluster function was deleted from exported ?
It was replaced by another one or it is no longer used?
The correct way for using the module is 
$Ticket = Connect-PveCluster...
... more calls of module functions with $Ticket as parameter

In Power shell 5.1 I'm not able to import it obtaining the followin error message.
DETTAGLIATO: Caricamento del modulo dal percorso 'C:\Users\xxx\Documents\WindowsPowerShell\Modules\Corsinvest.ProxmoxVE.Api\Corsinvest.ProxmoxVE.Api.psd1'.
DETTAGLIATO: Caricamento del modulo dal percorso 'C:\Users\xxx\Documents\WindowsPowerShell\Modules\Corsinvest.ProxmoxVE.Api\Corsinvest.ProxmoxVE.Api.psm1'.
In C:\Users\xxx\Documents\WindowsPowerShell\Modules\Corsinvest.ProxmoxVE.Api\Corsinvest.ProxmoxVE.Api.psm1:235 car:55
+                     $Parameters[$_] = $Parameters[$_] ? 1 : 0
+                                                       ~
Token '?' imprevisto nell'espressione o nell'istruzione.
In C:\Users\xxx\Documents\WindowsPowerShell\Modules\Corsinvest.ProxmoxVE.Api\Corsinvest.ProxmoxVE.Api.psm1:355 car:84
+ ... t = (($TemplateFile -as [System.Uri]).Scheme -match '[http|https]') ?
+                                                                         ~
Token '?' imprevisto nell'espressione o nell'istruzione.
In C:\Users\xxx\Documents\WindowsPowerShell\Modules\Corsinvest.ProxmoxVE.Api\Corsinvest.ProxmoxVE.Api.psm1:356 car:63
+                     (Invoke-WebRequest $TemplateFile).Content :
+                                                               ~
Token ':' imprevisto nell'espressione o nell'istruzione.
In C:\Users\xxx\Documents\WindowsPowerShell\Modules\Corsinvest.ProxmoxVE.Api\Corsinvest.ProxmoxVE.Api.psm1:11 car:22
+ ... ValidVmId : System.Management.Automation.IValidateSetValuesGenerator  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Impossibile trovare il tipo [System.Management.Automation.IValidateSetValuesGenerator].
In C:\Users\xxx\Documents\WindowsPowerShell\Modules\Corsinvest.ProxmoxVE.Api\Corsinvest.ProxmoxVE.Api.psm1:17 car:24
+ ... lidVmName : System.Management.Automation.IValidateSetValuesGenerator  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Impossibile trovare il tipo [System.Management.Automation.IValidateSetValuesGenerator].
In C:\Users\xxx\Documents\WindowsPowerShell\Modules\Corsinvest.ProxmoxVE.Api\Corsinvest.ProxmoxVE.Api.psm1:23 car:22
+ ... ValidNode : System.Management.Automation.IValidateSetValuesGenerator  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Impossibile trovare il tipo [System.Management.Automation.IValidateSetValuesGenerator].
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken
 
Import-Module : Impossibile elaborare il modulo 'Corsinvest.ProxmoxVE.Api.psm1' elencato nel campo 'ModuleToProcess/RootModule' del manifesto del modulo 
'C:\Users\xxx\Documents\WindowsPowerShell\Modules\Corsinvest.ProxmoxVE.Api\Corsinvest.ProxmoxVE.Api.psd1'. Non sono stati trovati moduli validi in alcuna directory di moduli.
In riga:1 car:1
+ Import-Module  C:\Users\xxx\Documents\WindowsPowerShell\Modules\Co ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (Corsinvest.ProxmoxVE.Api:String) [Import-Module], PSInvalidOperationException
    + FullyQualifiedErrorId : Modules_ModuleFileNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

Thank for the great work

**Comment by franklupo** [comment]
HI,
the first is an error. Im using PowerShell 7.1

Best regards

**Comment by franklupo** [comment]
News?
